/** JS 镜像，仅地图 / Canvas 等读不到 CSS 变量的地方使用。 */
export const designTokens = {
  colorBrandPrimary: '#2F7A4D',
  colorBrandPrimaryDark: '#245E3B',
  colorBrandPrimarySoft: '#E9F3ED',
  colorOnBrand: '#FFFFFF',
  colorSuccess: '#2F7A4D',
  colorSuccessDark: '#245E3B',
  colorSuccessSoft: '#E9F3ED',
  colorWarning: '#DE8A3B',
  colorWarningDark: '#A9631F',
  colorWarningSoft: '#FDF1E4',
  colorInfo: '#3D7CB0',
  colorInfoDark: '#2C6188',
  colorInfoSoft: '#E8F1F8',
  colorDanger: '#C9553F',
  colorDangerDark: '#A03F2C',
  colorDangerSoft: '#FBECEA',
  colorPurple: '#7A6BB5',
  colorPurpleDark: '#5E4E9E',
  colorPurpleSoft: '#F0EDFA',
  colorGold: '#C99A4E',
  colorGoldDark: '#8C6A2E',
  colorGoldSoft: '#FBF3E6',
  colorPrice: '#D2543C',
  colorBg: '#F4F7F2',
  colorCard: '#FFFFFF',
  colorCardAlt: '#FCFDFC',
  colorInk: '#1D2A22',
  colorInk2: '#5E6F64',
  colorInk3: '#9AA8A0',
  colorTextNav: '#41504A',
  colorLine: '#E7ECE6',
  colorLineLight: '#F1F5F0',
  colorHoverBg: '#FAFCFA',
  colorTabbarDefault: '#9AA8A0',
  colorTabbarActive: '#245E3B',
  colorBgCream: '#FBF8F2',
  colorSidebarGradStart: '#22303F',
  colorSidebarGradEnd: '#1A2530',
  colorSidebarText: '#AEBFCE',
  colorSidebarBg: '#FFFFFF',
  colorSidebarActiveBg: '#E9F3ED',
  colorFocusRing: 'rgba(47, 122, 77, 0.22)',
  colorChartFill: 'rgba(47, 122, 77, 0.08)',
  radiusCard: 14,
  radiusIcon: 11,
  radiusButton: 12,
  radiusPill: 20,
  radiusNav: 10,
  spacePage: 16,
  spaceSection: 16,
  spaceCard: 14,
  spaceGap: 12,
  controlSize: 44,
  textTitle: 20,
  textSubtitle: 16,
  textBody: 14,
  textCaption: 12
} as const

export type DesignTokens = typeof designTokens
